import fs from "node:fs";
import path from "node:path";
import { memberOf } from "../domain/lookup.ts";

const ORCHESTRATOR = path.join(import.meta.dir, "..");
const REPO_ROOT = path.join(ORCHESTRATOR, "..");
const DEFAULT_OUT = path.join(REPO_ROOT, "docs", "bdd.md");

const TEST_START = /^ {2}(?:test|testInTempDirs)\(\s*"((?:[^"\\]|\\.)*)"/gm;
const DESCRIBE_START = /^describe\(\s*"((?:[^"\\]|\\.)*)"/gm;
const STEP = /^\s*\/\/ (Given|When|Then) (.+)$/gm;

const KEYWORDS = ["Given", "When", "Then"] as const;

const isKeyword = memberOf(KEYWORDS);

export interface Step {
  keyword: (typeof KEYWORDS)[number];
  text: string;
}

export interface Case {
  name: string;
  steps: Step[];
}

export interface Suite {
  name: string;
  cases: Case[];
}

export interface File {
  path: string;
  suites: Suite[];
}

function suiteFiles(dir: string): string[] {
  const found: string[] = [];

  const walk = (current: string) => {
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const full = path.join(current, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else if (entry.name.endsWith(".test.ts")) {
        found.push(full);
      }
    }
  };

  walk(dir);
  return found.sort();
}

function marks(
  source: string,
  pattern: RegExp,
): { at: number; name: string }[] {
  return [...source.matchAll(pattern)].map((match) => ({
    at: match.index,
    name: match[1]!,
  }));
}

function stepsIn(source: string): Step[] {
  return [...source.matchAll(STEP)].map((match) => {
    const keyword = match[1]!;
    if (!isKeyword(keyword)) {
      throw new Error(`"${keyword}" is not a step keyword`);
    }
    return { keyword, text: match[2]! };
  });
}

export function readFile(filePath: string): File {
  const source = fs.readFileSync(filePath, "utf-8");
  const describes = marks(source, DESCRIBE_START);
  const tests = marks(source, TEST_START);

  const suites: Suite[] = describes.map((one) => ({
    name: one.name,
    cases: [],
  }));

  for (const [index, test] of tests.entries()) {
    const ends = tests[index + 1]?.at ?? source.length;
    const owner = describes.findLastIndex((one) => one.at < test.at);
    if (owner === -1) {
      continue;
    }
    suites[owner]!.cases.push({
      name: test.name,
      steps: stepsIn(source.slice(test.at, ends)),
    });
  }

  return { path: path.relative(REPO_ROOT, filePath), suites };
}

export function render(files: File[]): string {
  const cases = files.flatMap((file) =>
    file.suites.flatMap((suite) => suite.cases),
  );
  const out: string[] = [
    "# Behaviour",
    "",
    "Every Given, When and Then in the suite, in the order they are written.",
    "Generated by `bun run bdd` from `orchestrator/testing/bdd-doc.ts` — edit the",
    "tests, not this file. How one is written is [Behaviour tests](bdd-tests.md).",
    "",
    `${cases.length} behaviours across ${files.length} suites.`,
    "",
  ];

  for (const file of files) {
    out.push(`## ${file.path}`, "");
    for (const suite of file.suites) {
      out.push(`### ${suite.name}`, "");
      for (const one of suite.cases) {
        out.push(`#### ${one.name}`, "");
        for (const step of one.steps) {
          out.push(`- **${step.keyword}** ${step.text}`);
        }
        out.push("");
      }
    }
  }

  return `${out.join("\n").replace(/\n+$/, "")}\n`;
}

if (import.meta.main) {
  const out = process.argv[2] ?? DEFAULT_OUT;
  const files = suiteFiles(ORCHESTRATOR).map(readFile);
  fs.writeFileSync(out, render(files), "utf-8");
  const cases = files.reduce(
    (total, file) =>
      total + file.suites.reduce((sum, suite) => sum + suite.cases.length, 0),
    0,
  );
  process.stdout.write(
    `${out}: ${cases} behaviours from ${files.length} suites\n`,
  );
}
